# Site settings
title: topher6345.github.io	
email: topher@tophersaunders.com
description: Software Engineer, Santa Cruz
baseurl: ""
url: "http://tophersaunders.com"
username: topher6345
twitter: snophort
future: false

# Build settings
markdown: redcarpet
input: GFM
permalink: :title
