# Site settings
title: Tophersaunders.com	
email: topher@tophersaunders.com
description: "Web Developer, Code Addict, Sound Wizard"
baseurl: ""
url: "http://tophersaunders.com"
username: topher6345
twitter: snophort
future: false

# Build settings
markdown: redcarpet
input: GFM
permalink: :title
