# Site settings
title: topher6345.github.io
email: topher6345@gmail.com
description: Full-stack Web Software Engineer in San Fancisco, CA
baseurl: ""
url: "http://tophersaunders.com"
username: topher6345
twitter: snophort
future: false

# Build settings
markdown: redcarpet
input: GFM
permalink: :title
